patches/packages/{python-babel, python-flask-babel}: import patches from upstream
Import bump patches for python-babel and python-flask-babel, due to fixing
install error for reForis. -TEST TEST TEST TEST

Fixing:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from pathlib import Path;print(Path(__import__("reforis").__file__).parent.parent)
                                        ~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/reforis/__init__.py", line 24, in <module>
  File "/usr/lib/python3.13/site-packages/reforis/locale.py", line 25, in <module>
  File "/usr/lib/python3.13/site-packages/flask_babel/__init__.py", line 19, in <module>
ImportError: cannot import name 'locked_cached_property' from 'flask.helpers' (/usr/lib/python3.13/site-packages/flask/helpers.pyc)