README: add g++-multilib as requirement
While building node packages on Ubuntu 20.04 LTS, node fails because of:

In file included from /usr/include/c++/9/deque:60,
                 from /usr/include/c++/9/queue:60,
                 from ../deps/v8/src/libplatform/default-foreground-task-runner.h:8,
                 from ../deps/v8/src/libplatform/default-foreground-task-runner.cc:5:
/usr/include/c++/9/bits/stl_algobase.h:59:10: fatal error: bits/c++config.h: No such file or directory
   59 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

This can be solved by installing g++-multilib