patches/openwrt/uboot-tools: Fix compilation error due to missing setuptools
Added setuptools/host as dependency to fix compilation.

Fixes:
```
Traceback (most recent call last):
 File "/.../build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/u-boot-2025.10/scripts/dtc/pylibfdt/setup.py", line 23, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'
```