configs/common: essential_packages: wget renamed to wget-ssl
In recent change in packages repository, we want to ensure that wget-ssl
is essential package. This fixes following error:

ERROR: Config option is not present in generated config: CONFIG_PACKAGE_wget=y