patches/packages/tio: fix compilation error due to missing nls
Fix compilation error due to missing nls library.
Fixing error:
../arm-openwrt-linux-muslgnueabi/bin/ld.bfd: cannot find -lintl: No such file or directory