patches/packages/libinput: fix missing native language support
Added NLS dependency and fixing compilation error:

libglib-2.0.so.0: undefined reference to `libiconv'
libglib-2.0.so.0: undefined reference to `libiconv_open'
libglib-2.0.so.0: undefined reference to `libintl_bind_textdomain_codeset'
libglib-2.0.so.0: undefined reference to `libiconv_close'
libglib-2.0.so.0: undefined reference to `libintl_dcgettext'
libglib-2.0.so.0: undefined reference to `libintl_textdomain'
libglib-2.0.so.0: undefined reference to `libintl_bindtextdomain'
libglib-2.0.so.0: undefined reference to `libintl_gettext'
libglib-2.0.so.0: undefined reference to `libintl_dgettext'
libglib-2.0.so.0: undefined reference to `libintl_dngettext'