README: Add gcc-multilib to dependencies
gcc-multilib is required on host for compiling luajit.
If it is not installed, luajit fails with this error:

fatal error: bits/libc-header-start.h: No such file or directory

We use Luajit for Knot Resolver, Suricata.