src/omnia-ng/linux: Add kernel-6.6 file to fix preparation
Fixes:
```
${BUILD_DIR}/include/kernel-version.mk:11: *** Missing kernel version/hash file for . Please create ${BUILD_DIR}/target/linux/generic/kernel-.  Stop.
make[4]: Leaving directory '${BUILD_DIR}/target/linux'
time: target/linux/prereq#0.01#0.00#0.02
    ERROR: target/linux failed to build.
```