patches/packages/fish: fix compilation error based on wrong linker
Fix compilation of fish package due to wrong provided linker. Switched to clean
linker instead of linker with ccache wrapper, because Cargo/Rust takes it as
argument not as usual ccache command with argument.

Fixing:
warning: `fish` (lib) generated 7 warnings (run `cargo fix --lib -p fish` to apply 7 suggestions)
error: linker `ccache powerpc-openwrt-linux-musl-gcc` not found
  |
  = note: No such file or directory (os error 2)