patches/packages/python-cryptography: Fix compilation due to using host python
Fix compilation error, which was caused by using local host python
instead of using SDK python during cross compilation.

Fixes:
```
  cargo:warning=/usr/include/python3.13/pyconfig.h:15:12: fatal error: arm-linux-gnueabihf/python3.13/pyconfig.h: No such file or directory
  cargo:warning=   15 | #  include <arm-linux-gnueabihf/python3.13/pyconfig.h>
  cargo:warning=      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
```