patches/{turris}packages: reForis DistUtils are now on PyPI
Host packages can installed only via pip and it is recommended to upload
it on PyPI. I was not able to get wheel from reForis Distutils without
it and when I didn't have it, there are no reForis packages

All the time it was failing with:
ERROR: Could not find a version that satisfies the requirement reforis_distutils (from versions: none)
ERROR: No matching distribution found for reforis_distutils
Traceback (most recent call last):
  File "/foo/mox/build/staging_dir/hostpkg/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/foo/mox/build/staging_dir/target-aarch64_cortex-a53_musl/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/foo/mox/build/staging_dir/hostpkg/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/foo/mox/build/tmp/tmp3s9rxjym', '--quiet', '--find-links', 'git+https://gitlab.nic.cz/turris/reforis/reforis-distutils.git#egg=reforis-distutils', 'reforis_distutils']' returned non-zero exit status 1.

I tried to change related rows in setup.py (reForis), but only what I was able to
do was to have (from versions: master instead of none) and even I specified exact
version then it could not find setup.py, but it looked promising.
Even though, locally I was able to have wheel, but not with OpenWrt build system.

There were changes in OpenWrt master (upcoming OpenWrt 20/21.xx) how
Host packages should look like and how they are done. Let's change it to
that approach according to:

https://github.com/openwrt/packages/tree/master/lang/python#host-side-python-packages-for-build

Since then it works as it should. :)