README.adoc: add "libyaml-dev" to debian dependencies
Debian package `libyaml-dev` is required on build host to successfully build package `kernel/linux`.

Otherwise we will get following errors:

mltree.o -L/build/staging_dir/target-aarch64_cortex-a53_musl/usr/lib -lyaml
/usr/bin/ld: skipping incompatible /build/staging_dir/target-aarch64_cortex-a53_musl/usr/lib/libyaml.so when searching for -lyaml
/usr/bin/ld: skipping incompatible /build/staging_dir/target-aarch64_cortex-a53_musl/usr/lib/libyaml.a when searching for -lyaml
/usr/bin/ld: cannot find -lyaml
/usr/bin/ld: skipping incompatible /build/staging_dir/target-aarch64_cortex-a53_musl/usr/lib/libyaml.so when searching for -lyaml
collect2: error: ld returned 1 exit status
time: package/kernel/linux/compile#2.05#0.33#2.39
    ERROR: package/kernel/linux failed to build.