README: add libc6-dev-i386 dependency
This dependency is required while compiling moonjit (it's luajit's
fork). Moonjit is used, for example, by Knot Resolver.
Otherwise, compilation fails with the following output:

/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
    7 | # include <gnu/stubs-32.h>
      |           ^~~~~~~~~~~~~~~~
compilation terminated.

Reported-by: Michal Vasilek <michal.vasilek@nic.cz>